---
title: "(research report title)"
author: "Ian Astalosh, Cassie Brooks, Catherine Chen, Jerry Xu, Leon Yao"
output: pdf_document
---

```{r, include=FALSE}
#PACKAGES
#install.packages(ggplot2)
#install.packages()
#install.packages()

#library(ggplot2)
#library()
#library()
```


# Executive Summary
This collaborative effort between nutrition and statistics departments aims to assess the impact of dietary fats on non-communicable diseases (NCD's). The data was taken from the Australian Health Survey 2011-2012 (AHS), at the time the largest health survey ever conducted in Australia. The main research questions we sought to answer were:

\begin{enumerate}
\item What factors influence the chances of a person having an NCD such as high cholesterol, Type II diabetes or dyslipidemia?
\item How significant is the intake of dietary fats on these chances?
\item Which dietary fats contribute more to these chances? Do different fats affect separate diseases in different ways?
\item Can we predict from these covariates whether a person has one of these diseases>
\end{enumerate}

We found \textbf{results}

# Context
NUTM intro


# Exploratory Data Analysis

## Missing Values
The data supplied for this project from the AHS contained 12,153 instances of 144 variables. After consultation with the experts in conjunction with our ultimate research goals, this was trimmed to 12,153 instances of 34 variables. 

The data firstly needed to be cleaned as there were large amounts of missingness. For variables that were identified as potential response variables, the missingness actually varied significantly:

(table)

For the cholesterol, HDL cholesterol and dyslipidemia in particular, there are only recorded responses for approximately a third of all repondents. We considered methods of dealing with the missingness such as multiple imputation, however ultimately deciding it doesn't make sense to impute the response variable for such large quantities of missingness, we decided to simply keep instances containing complete responses (no NAs). This loss was not actually too severe - when considering the 33% or so of measurements with measured responses, additionally removing left over NA's only removed ~10-20%. 

With each response having different levels of missingness, we use a different sample size for each test. 

## Dietary Fats
(tables of numbers of responses to be analysed ie. 4000 pos, 1500 neg etc.)

Dietary fat forms just one component of energy intake. Carbohydrates and sugars also make up a significant portion of a persons daily energy intake:

(boxplot1)

Using the HS data we can breakdown into the sources of individual fats (as a percentage of total intake)

(boxplot2)

We see saturated fats and trans-fatty acids make up the bulk of fats ingested by people, followed closely by monounsaturated fats. (probably a sentence about theoretical effects of these). The distributions are skewed as it appears some people may consume disproportionately large amounts of each. 

We can also examine the correlation structure of these fats:

(corrplot)

We see extremely strong relationships between alpha linoleic acid and polyunsaturated fat, and perhaps trans-fatty acids and saturated fat with only trans-fatty acids. Alpha linoleic acid is also correlated with polyunsatured fat. This relationships may be important to keep in mind as we try to assess the impact of individual fats on various comorbidities. 

# Models
We will use a number of classifiers to attempt to predict which patients have the non-communicable diseases of high cholsterol, type II diabetes, hypertension and dyslipidemia. We used a number of classifiers, however the two main classifiers we focus on are generalised linear models (logistic regressions) and random forests.
 
The reason for this is to take a more prediction based approach as well as a more inferential based approach. The random forest method was chosen as it is an extremely powerful classifcation algorithm, capable of handling different types of data and adept at preventing overfitting through its ensemble method. From this, we will gain highly optimized predictions of whether a person will or will not have a certain disease. However, it is limited in its scope in terms of interpretability, as it acts as somewhat of a black box model. From our random forests we will see which variables are most significant in determining the classification, but with no indication as to whether they are significant in a positive or negative way, for example.

Our logistic regression, alternatively, provides greater insight into the effect of each variable through its parameter estimates. While the error may be higher, we will more clearly be able to see the size and impact of the effect of each covariate. Specifically, this will enable us to examine which dietary fats positively and negatively impact a person's chances of disease.

We additionally fitted other classifiers such as KNN and CART for reference, however we are most interested in the GLMs and random forests. 



# Discussion




# References